from fastapi import FastAPI, WebSocket, WebSocketDisconnect, UploadFile, File, HTTPException
from fastapi.responses import FileResponse
from fastapi.middleware.cors import CORSMiddleware
from typing import List
import os
import json
import time
import logging
from aiofiles import open as aio_open
from agy_runner import run_agy_command, cancel_agy_command

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="AGY Chat Colab Bridge",
    description="WebSocket bridge between Android app and Antigravity CLI",
    version="1.0.0"
)

# Enable CORS for all origins (Android app + web)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class ConnectionManager:
    """Manages active WebSocket connections."""

    def __init__(self):
        self.active_connections: List[WebSocket] = []

    async def connect(self, websocket: WebSocket):
        await websocket.accept()
        self.active_connections.append(websocket)
        logger.info(f"Client connected. Total: {len(self.active_connections)}")

    def disconnect(self, websocket: WebSocket):
        if websocket in self.active_connections:
            self.active_connections.remove(websocket)
        logger.info(f"Client disconnected. Total: {len(self.active_connections)}")

    async def send(self, message: str, websocket: WebSocket):
        try:
            await websocket.send_text(message)
        except Exception as e:
            logger.warning(f"Failed to send message: {e}")

    async def broadcast(self, message: str):
        for connection in self.active_connections:
            await self.send(message, connection)


manager = ConnectionManager()


@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return {
        "status": "ok",
        "connected_clients": len(manager.active_connections),
        "service": "AGY Chat Colab Bridge"
    }


@app.get("/models")
async def get_models():
    """Return list of all supported AI models in Antigravity CLI."""
    from agy_runner import AVAILABLE_MODELS
    return {
        "models": AVAILABLE_MODELS,
        "count": len(AVAILABLE_MODELS)
    }


def resolve_colab_file_path(path_str: str) -> str:
    """Safely resolves file:/// URLs or relative paths to real file system locations."""
    clean = path_str.replace("file://", "").strip()
    if os.path.exists(clean) and not os.path.isdir(clean):
        return clean
    
    fname = os.path.basename(clean)
    search_roots = [
        "/root/.gemini/antigravity-cli/scratch",
        "/root/.gemini/antigravity-cli/brain",
        "/content/Next-Ai",
        "/content",
        "/tmp"
    ]
    for root_dir in search_roots:
        if os.path.exists(root_dir):
            for root, _, files in os.walk(root_dir):
                if fname in files:
                    candidate = os.path.join(root, fname)
                    if os.path.exists(candidate) and not os.path.isdir(candidate):
                        return candidate
    return clean


@app.get("/api/file")
async def get_file_content(path: str):
    """Fetch file content generated by Antigravity CLI tools."""
    resolved = resolve_colab_file_path(path)
    if not os.path.exists(resolved) or os.path.isdir(resolved):
        raise HTTPException(status_code=404, detail=f"File not found: {path}")
    try:
        with open(resolved, "r", encoding="utf-8", errors="replace") as f:
            content = f.read()
        return {
            "status": "ok",
            "filename": os.path.basename(resolved),
            "path": resolved,
            "size": os.path.getsize(resolved),
            "content": content
        }
    except Exception as e:
        logger.error(f"Error reading file {resolved}: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/api/file/download")
async def download_file(path: str):
    """Download file generated by Antigravity CLI tools directly."""
    resolved = resolve_colab_file_path(path)
    if not os.path.exists(resolved) or os.path.isdir(resolved):
        raise HTTPException(status_code=404, detail=f"File not found: {path}")
    fname = os.path.basename(resolved)
    return FileResponse(
        path=resolved,
        filename=fname,
        media_type="application/octet-stream"
    )


@app.post("/upload")
async def upload_file(file: UploadFile = File(...)):
    """Accept file upload from Android app, save to /tmp."""
    try:
        # Sanitize filename
        safe_name = os.path.basename(file.filename or "upload")
        file_path = f"/tmp/agychat_{safe_name}"
        async with aio_open(file_path, "wb") as out_file:
            content = await file.read()
            await out_file.write(content)
        logger.info(f"Uploaded file: {file_path} ({len(content)} bytes)")
        return {
            "filename": safe_name,
            "path": file_path,
            "size": len(content),
            "status": "uploaded"
        }
    except Exception as e:
        logger.error(f"Upload failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/api/sync/backup")
async def api_sync_backup(payload: dict):
    """Receive full Next AI app state and save directly to Google Drive."""
    try:
        drive_dir = "/content/drive/MyDrive/NextAI_Backup"
        os.makedirs(drive_dir, exist_ok=True)
        backup_path = os.path.join(drive_dir, "nextai_app_cloud_backup.json")
        with open(backup_path, "w") as f:
            json.dump(payload, f, indent=2)

        os.makedirs("/tmp/nextai_backup", exist_ok=True)
        with open("/tmp/nextai_backup/nextai_app_cloud_backup.json", "w") as f:
            json.dump(payload, f, indent=2)

        logger.info(f"Successfully saved cloud backup to {backup_path}")
        return {
            "status": "success",
            "message": "Saved to Google Drive (/MyDrive/NextAI_Backup)",
            "path": backup_path,
            "timestamp": time.time()
        }
    except Exception as e:
        logger.error(f"Cloud backup failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/api/sync/restore")
async def api_sync_restore():
    """Read full Next AI app state from Google Drive."""
    candidate_paths = [
        "/content/drive/MyDrive/NextAI_Backup/nextai_app_cloud_backup.json",
        "/content/drive/MyDrive/NextAI_Backup/nextai_app_sync.json",
        "/tmp/nextai_backup/nextai_app_cloud_backup.json"
    ]
    for p in candidate_paths:
        if os.path.exists(p):
            try:
                with open(p, "r") as f:
                    data = json.load(f)
                return {"status": "success", "data": data, "source": p}
            except Exception as e:
                logger.error(f"Failed to read backup from {p}: {e}")

    raise HTTPException(status_code=404, detail="No cloud backup found on Google Drive")


@app.get("/api/sync/status")
async def api_sync_status():
    """Return Google Drive mount and backup status."""
    drive_mounted = os.path.exists("/content/drive/MyDrive")
    backup_file = "/content/drive/MyDrive/NextAI_Backup/nextai_app_cloud_backup.json"
    exists = os.path.exists(backup_file)
    size = os.path.getsize(backup_file) if exists else 0
    mtime = os.path.getmtime(backup_file) if exists else 0
    return {
        "drive_mounted": drive_mounted,
        "backup_exists": exists,
        "backup_size_bytes": size,
        "backup_timestamp": mtime
    }


@app.get("/history")
async def get_history():
    """Return list of AGY conversation history files."""
    history_dir = os.path.expanduser("~/.gemini/antigravity-cli/brain")
    history_files = []
    try:
        if os.path.exists(history_dir):
            for root, dirs, files in os.walk(history_dir):
                for f in files:
                    if f.endswith(".jsonl"):
                        full_path = os.path.join(root, f)
                        stat = os.stat(full_path)
                        history_files.append({
                            "path": full_path,
                            "name": f,
                            "size": stat.st_size,
                            "modified": stat.st_mtime
                        })
        # Sort by most recent first
        history_files.sort(key=lambda x: x["modified"], reverse=True)
        return {"history_files": history_files, "count": len(history_files)}
    except Exception as e:
        logger.error(f"Failed to fetch history: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    """
    Main WebSocket endpoint.
    
    Protocol (JSON):
      Client → Server: {"message": "...", "conversation_id": "..."}
      Server → Client: {"type": "chunk"|"done"|"error"|"info", "content": "...", "timestamp": ...}
    """
    await manager.connect(websocket)

    # Send welcome handshake
    await manager.send(
        json.dumps({"type": "connected", "content": "AGY Chat Bridge ready"}),
        websocket
    )

    # Keep-alive ping task to prevent Cloudflare 100s WebSocket timeout
    async def ping_task():
        while True:
            await asyncio.sleep(45)
            try:
                await manager.send(
                    json.dumps({"type": "ping", "content": "", "timestamp": time.time()}),
                    websocket
                )
            except Exception:
                break

    import asyncio as _asyncio
    ping_job = _asyncio.create_task(ping_task())

    try:
        while True:
            raw = await websocket.receive_text()
            logger.info(f"Received: {raw[:200]}")

            # Parse incoming message
            user_message = raw
            conv_id = ""
            effort = "high"
            model = ""
            memories = []
            try:
                payload = json.loads(raw)
                # Handle stream cancellation request
                if payload.get("type") == "cancel":
                    cancel_id = payload.get("conversation_id", "")
                    logger.info(f"Cancellation requested for conversation: {cancel_id}")
                    cancelled = cancel_agy_command(cancel_id)
                    await manager.send(json.dumps({
                        "type": "done",
                        "content": "[Generation stopped by user]",
                        "timestamp": time.time() if "time" in globals() else 0
                    }), websocket)
                    continue

                # Handle Cloud Sync Backup request
                if payload.get("action") == "cloud_sync_backup":
                    b_data = payload.get("backup_data", {})
                    try:
                        drive_dir = "/content/drive/MyDrive/NextAI_Backup"
                        os.makedirs(drive_dir, exist_ok=True)
                        b_path = os.path.join(drive_dir, "nextai_app_cloud_backup.json")
                        with open(b_path, "w") as f:
                            json.dump(b_data, f, indent=2)

                        os.makedirs("/tmp/nextai_backup", exist_ok=True)
                        with open("/tmp/nextai_backup/nextai_app_cloud_backup.json", "w") as f:
                            json.dump(b_data, f, indent=2)

                        logger.info("Successfully processed cloud sync backup")
                        await manager.send(json.dumps({
                            "type": "cloud_sync_result",
                            "status": "success",
                            "message": "Saved to Google Drive (/MyDrive/NextAI_Backup)",
                            "timestamp": time.time() * 1000
                        }), websocket)
                    except Exception as b_err:
                        logger.error(f"Cloud sync backup failed: {b_err}")
                        await manager.send(json.dumps({
                            "type": "cloud_sync_result",
                            "status": "error",
                            "message": f"Drive backup failed: {b_err}"
                        }), websocket)
                    continue

                # Handle Cloud Sync Restore request
                if payload.get("action") == "cloud_sync_restore":
                    candidate_paths = [
                        "/content/drive/MyDrive/NextAI_Backup/nextai_app_cloud_backup.json",
                        "/content/drive/MyDrive/NextAI_Backup/nextai_app_sync.json",
                        "/tmp/nextai_backup/nextai_app_cloud_backup.json"
                    ]
                    found_data = None
                    for p in candidate_paths:
                        if os.path.exists(p):
                            try:
                                with open(p, "r") as f:
                                    found_data = json.load(f)
                                break
                            except Exception:
                                pass

                    if found_data is not None:
                        logger.info("Sent cloud restore data back to client")
                        await manager.send(json.dumps({
                            "type": "cloud_restore_data",
                            "status": "success",
                            "data": found_data
                        }), websocket)
                    else:
                        await manager.send(json.dumps({
                            "type": "cloud_restore_data",
                            "status": "error",
                            "message": "No backup found in Google Drive (/MyDrive/NextAI_Backup)"
                        }), websocket)
                    continue

                # Handle get_file request for artifacts / workspace files
                if payload.get("action") == "get_file":
                    req_path = payload.get("path", "")
                    resolved = resolve_colab_file_path(req_path)
                    if os.path.exists(resolved) and not os.path.isdir(resolved):
                        try:
                            with open(resolved, "r", encoding="utf-8", errors="replace") as f:
                                f_content = f.read()
                            await manager.send(json.dumps({
                                "type": "file_data",
                                "status": "ok",
                                "path": resolved,
                                "filename": os.path.basename(resolved),
                                "content": f_content,
                                "size": os.path.getsize(resolved)
                            }), websocket)
                        except Exception as f_err:
                            await manager.send(json.dumps({
                                "type": "file_data",
                                "status": "error",
                                "message": f"Could not read file: {f_err}"
                            }), websocket)
                    else:
                        await manager.send(json.dumps({
                            "type": "file_data",
                            "status": "error",
                            "message": f"File not found on server: {req_path}"
                        }), websocket)
                    continue

                user_message = payload.get("message", raw)
                conv_id = payload.get("conversation_id", "")
                effort = payload.get("effort", "high")
                model = payload.get("model", "")
                memories = payload.get("memories", [])
                custom_instructions = payload.get("custom_instructions")
                personalization = payload.get("personalization")  # Full Personalization profile
                auto_memory = payload.get("auto_memory", True)
                is_temporary = payload.get("is_temporary", False)
                history = payload.get("history", [])  # Multi-turn conversation turns for full context retention

                # Multi-attachment files processing
                attached_files = payload.get("files", [])
                if not attached_files and payload.get("file_name") and payload.get("file_data"):
                    attached_files = [{
                        "name": payload.get("file_name"),
                        "data": payload.get("file_data"),
                        "is_image": payload.get("file_is_image", False)
                    }]

                file_prefixes = []
                if attached_files:
                    import base64
                    os.makedirs("/tmp/uploads", exist_ok=True)
                    for f_idx, f_item in enumerate(attached_files):
                        try:
                            f_name = f_item.get("name", f"file_{f_idx}")
                            f_data = f_item.get("data")
                            if f_data:
                                s_name = f"{f_idx}_{os.path.basename(f_name)}"
                                s_path = f"/tmp/uploads/{s_name}"
                                with open(s_path, "wb") as f_out:
                                    f_out.write(base64.b64decode(f_data))
                                file_prefixes.append(f"[User attached file: {s_path}]")
                                logger.info(f"Saved uploaded attachment: {s_path}")
                        except Exception as f_err:
                            logger.error(f"Failed to process attachment {f_idx}: {f_err}")

                if file_prefixes:
                    user_message = "\n".join(file_prefixes) + "\n\n" + user_message
            except json.JSONDecodeError:
                user_message = raw  # Treat as plain text
                custom_instructions = None
                personalization = None
                auto_memory = True
                is_temporary = False
                history = []

            # Stream agy command with full personalization profile, memories, and model settings
            async for event in run_agy_command(
                user_message,
                conv_id,
                effort,
                model,
                memories,
                custom_instructions=custom_instructions,
                personalization=personalization,
                is_auto_memory=auto_memory,
                is_temporary=is_temporary,
                history=history
            ):
                await manager.send(event, websocket)

    except WebSocketDisconnect:
        ping_job.cancel()
        manager.disconnect(websocket)
        logger.info("WebSocket client disconnected normally")
    except Exception as e:
        ping_job.cancel()
        logger.error(f"WebSocket error: {e}")
        manager.disconnect(websocket)
