package com.agychat.app.ui.settings

import android.content.Context
import android.content.Intent
import android.widget.Toast
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.hilt.navigation.compose.hiltViewModel
import com.agychat.app.domain.model.ConnectionState
import com.agychat.app.ui.chat.ChatViewModel

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SettingsScreen(
    onBack: () -> Unit,
    chatViewModel: ChatViewModel = hiltViewModel()
) {
    val context = LocalContext.current
    val prefs = remember { context.getSharedPreferences("next_ai_prefs", Context.MODE_PRIVATE) }
    val connectionState by chatViewModel.connectionState.collectAsState()

    var serverUrl by remember {
        mutableStateOf(
            prefs.getString("server_url", "wss://english-memories-opens-judicial.trycloudflare.com/ws") ?: "wss://english-memories-opens-judicial.trycloudflare.com/ws"
        )
    }
    var driveAutoBackup by remember {
        mutableStateOf(prefs.getBoolean("drive_auto_backup", true))
    }
    var reasoningEffort by remember {
        mutableStateOf(prefs.getString("reasoning_effort", "high") ?: "high")
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Text(
                        text = "Settings",
                        style = MaterialTheme.typography.titleLarge,
                        fontWeight = FontWeight.Bold
                    )
                },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.Default.ArrowBack, contentDescription = "Back")
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.surface
                )
            )
        },
        containerColor = MaterialTheme.colorScheme.background
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(horizontal = 16.dp)
                .verticalScroll(rememberScrollState()),
            verticalArrangement = Arrangement.spacedBy(14.dp)
        ) {
            Spacer(Modifier.height(4.dp))

            // ── Section 1: Colab Bridge Connection ────────────────────────
            SettingsCard(
                title = "Colab Bridge Server",
                icon = Icons.Default.Wifi,
                badge = when (connectionState) {
                    ConnectionState.CONNECTED -> "ONLINE" to Color(0xFF4CAF50)
                    ConnectionState.CONNECTING -> "CONNECTING" to Color(0xFFFFB300)
                    ConnectionState.ERROR -> "ERROR" to Color(0xFFEF5350)
                    ConnectionState.DISCONNECTED -> "OFFLINE" to Color(0xFF9E9E9E)
                }
            ) {
                Text(
                    text = "Enter the secure WebSocket URL generated by your Colab terminal bridge (Cloudflare or ngrok tunnel).",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    lineHeight = 18.sp
                )

                Spacer(Modifier.height(10.dp))

                OutlinedTextField(
                    value = serverUrl,
                    onValueChange = { serverUrl = it },
                    label = { Text("WebSocket URL") },
                    placeholder = { Text("wss://xxxx.trycloudflare.com/ws") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(12.dp)
                )

                Spacer(Modifier.height(10.dp))

                Button(
                    onClick = {
                        val trimmed = serverUrl.trim()
                        prefs.edit().putString("server_url", trimmed).apply()
                        chatViewModel.connectToServer(trimmed)
                        Toast.makeText(context, "Connecting to $trimmed...", Toast.LENGTH_SHORT).show()
                    },
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(12.dp)
                ) {
                    Icon(Icons.Default.Refresh, contentDescription = null, modifier = Modifier.size(16.dp))
                    Spacer(Modifier.width(6.dp))
                    Text("Connect to CLI")
                }
            }

            // ── Section 2: AI Reasoning & Agent Configuration ─────────────
            SettingsCard(
                title = "Agent Reasoning & CLI",
                icon = Icons.Default.Psychology
            ) {
                Text(
                    text = "Configure reasoning depth and tool permissions for the active Antigravity CLI session.",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )

                Spacer(Modifier.height(12.dp))

                Text(
                    text = "Reasoning Effort:",
                    style = MaterialTheme.typography.titleSmall
                )

                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(vertical = 6.dp),
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    listOf("low", "medium", "high").forEach { effort ->
                        val isSelected = reasoningEffort == effort
                        OutlinedButton(
                            onClick = {
                                reasoningEffort = effort
                                prefs.edit().putString("reasoning_effort", effort).apply()
                            },
                            modifier = Modifier.weight(1f),
                            shape = RoundedCornerShape(10.dp),
                            colors = ButtonDefaults.outlinedButtonColors(
                                containerColor = if (isSelected) MaterialTheme.colorScheme.primaryContainer else Color.Transparent
                            )
                        ) {
                            Text(
                                text = effort.uppercase(),
                                style = MaterialTheme.typography.labelSmall,
                                fontWeight = if (isSelected) FontWeight.Bold else FontWeight.Normal
                            )
                        }
                    }
                }
            }

            // ── Section 3: Backup & Export ────────────────────────────────
            SettingsCard(
                title = "Backup & Cloud Storage",
                icon = Icons.Default.CloudSync
            ) {
                Text(
                    text = "Preserve your conversation history, artifacts, and slash command outputs.",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )

                Spacer(Modifier.height(12.dp))

                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Column(modifier = Modifier.weight(1f)) {
                        Text(text = "Auto-save to Local & Drive", style = MaterialTheme.typography.titleSmall)
                        Text(
                            text = "Save conversations automatically after each turn",
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                    Switch(
                        checked = driveAutoBackup,
                        onCheckedChange = {
                            driveAutoBackup = it
                            prefs.edit().putBoolean("drive_auto_backup", it).apply()
                        }
                    )
                }

                Spacer(Modifier.height(10.dp))

                OutlinedButton(
                    onClick = {
                        val md = chatViewModel.exportConversationToMarkdown()
                        val sendIntent = Intent().apply {
                            action = Intent.ACTION_SEND
                            putExtra(Intent.EXTRA_TEXT, md)
                            type = "text/plain"
                        }
                        context.startActivity(Intent.createChooser(sendIntent, "Export Chat as Markdown"))
                    },
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(12.dp)
                ) {
                    Icon(Icons.Default.Download, null, Modifier.size(16.dp))
                    Spacer(Modifier.width(6.dp))
                    Text("Export All Chats (Markdown)")
                }
            }

            // ── Section 4: About & System ─────────────────────────────────
            SettingsCard(
                title = "About Next AI",
                icon = Icons.Default.Info
            ) {
                Text(
                    text = "Next AI v1.1.0",
                    style = MaterialTheme.typography.titleSmall,
                    fontWeight = FontWeight.Bold
                )
                Text(
                    text = "Connected Pair-Programming Assistant for Google Antigravity CLI.\nSupports /boost, /goal, /plan, /schedule, /browser, /learn, and multi-turn streaming.",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    lineHeight = 18.sp
                )
            }

            Spacer(Modifier.height(24.dp))
        }
    }
}

@Composable
fun SettingsCard(
    title: String,
    icon: ImageVector,
    badge: Pair<String, Color>? = null,
    content: @Composable ColumnScope.() -> Unit
) {
    Card(
        modifier = Modifier
            .fillMaxWidth()
            .border(1.dp, MaterialTheme.colorScheme.outlineVariant, RoundedCornerShape(16.dp)),
        shape = RoundedCornerShape(16.dp),
        colors = CardDefaults.cardColors(
            containerColor = MaterialTheme.colorScheme.surface
        )
    ) {
        Column(modifier = Modifier.padding(16.dp)) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Box(
                        modifier = Modifier
                            .size(32.dp)
                            .clip(RoundedCornerShape(8.dp))
                            .background(MaterialTheme.colorScheme.primary.copy(alpha = 0.15f)),
                        contentAlignment = Alignment.Center
                    ) {
                        Icon(
                            imageVector = icon,
                            contentDescription = null,
                            tint = MaterialTheme.colorScheme.primary,
                            modifier = Modifier.size(18.dp)
                        )
                    }
                    Spacer(Modifier.width(10.dp))
                    Text(
                        text = title,
                        style = MaterialTheme.typography.titleMedium,
                        fontWeight = FontWeight.Bold
                    )
                }

                if (badge != null) {
                    val (label, bColor) = badge
                    Text(
                        text = label,
                        style = MaterialTheme.typography.labelSmall,
                        fontWeight = FontWeight.Bold,
                        color = bColor,
                        modifier = Modifier
                            .clip(RoundedCornerShape(6.dp))
                            .background(bColor.copy(alpha = 0.15f))
                            .padding(horizontal = 6.dp, vertical = 2.dp)
                    )
                }
            }

            Spacer(Modifier.height(12.dp))
            content()
        }
    }
}
